# Generated by Django 5.2.4 on 2026-09-23 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("max_turns", models.PositiveIntegerField(default=4)),
                ("temperature_target", models.FloatField(default=0.7)),
                ("temperature_auditor", models.FloatField(default=0.2)),
                ("temperature_judge", models.FloatField(default=0.0)),
                ("top_p", models.FloatField(default=1.0)),
                ("max_tokens", models.PositiveIntegerField(default=2048)),
                ("retry_policy", models.JSONField(blank=True, default=dict)),
                ("timeout_seconds", models.PositiveIntegerField(default=300)),
                ("concurrency", models.PositiveIntegerField(default=1)),
                ("language", models.CharField(default="en", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_profiles",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_profile",
                "ordering": ["project__name", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "name"),
                        name="unique_audit_profile_name_per_project",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=250)),
                ("provider", models.CharField(max_length=120)),
                ("base_url", models.URLField()),
                ("model_id", models.CharField(max_length=250)),
                ("model_revision", models.CharField(blank=True, max_length=250)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("default_parameters", models.JSONField(blank=True, default=dict)),
                ("secret_reference", models.CharField(blank=True, max_length=250)),
                (
                    "api_key_direct",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_endpoints",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_model_endpoint",
                "ordering": ["project__name", "display_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "display_name"),
                        name="unique_model_endpoint_display_name_per_project",
                    )
                ],
            },
        ),
    ]
