# Generated by Django 5.2.4 on 2026-09-24 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=250)),
                ('provider', models.CharField(max_length=120)),
                ('base_url', models.URLField()),
                ('model_id', models.CharField(max_length=250)),
                ('model_revision', models.CharField(blank=True, max_length=250)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('secret_reference', models.CharField(blank=True, max_length=250)),
                ('api_key_direct', models.CharField(blank=True, default='', max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_endpoints', to='accounts.project')),
            ],
            options={
                'db_table': 'core_model_endpoint',
                'ordering': ['project__name', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'display_name'), name='unique_model_endpoint_display_name_per_project')],
            },
        ),
        migrations.CreateModel(
            name='ModelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('provider', models.CharField(default='openai', max_length=120)),
                ('base_url', models.URLField()),
                ('secret_reference', models.CharField(blank=True, max_length=250)),
                ('api_key_direct', models.CharField(blank=True, default='', max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_connections', to='accounts.project')),
            ],
            options={
                'db_table': 'core_model_connection',
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=250)),
                ('model_id', models.CharField(max_length=250)),
                ('model_revision', models.CharField(blank=True, max_length=250)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='model_registry.modelconnection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_models', to='accounts.project')),
            ],
            options={
                'db_table': 'core_registered_model',
                'ordering': ['connection__name', 'display_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='modelconnection',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_connection_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='registeredmodel',
            constraint=models.UniqueConstraint(fields=('connection', 'model_id'), name='unique_model_id_per_connection'),
        ),
    ]
