# Generated by Django 5.2.4 on 2026-09-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_audit_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.PositiveBigIntegerField(db_index=True)),
                ("version_item_id", models.CharField(db_index=True, max_length=64)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_audit_event",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["run_id", "id"], name="audit_event_run_id_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ScenarioResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.PositiveBigIntegerField()),
                ("version_item_id", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_scenario_result",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "version_item_id"),
                        name="unique_scenario_result_per_run_item",
                    )
                ],
            },
        ),
    ]
