# Generated by Django 5.2.4 on 2026-09-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_scenarioresult_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelendpoint",
            name="api_key_direct",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
