# Generated by Django 5.2.4 on 2026-09-23 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=300)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_scenario",
                "ordering": ["project__name", "key"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("expected_behavior", models.JSONField(default=list)),
                ("test_prompt", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="scenarios.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "core_scenario_revision",
                "ordering": ["scenario_id", "revision"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_sets",
                        to="accounts.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_scenario_set",
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioSetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("scenario_count", models.PositiveIntegerField()),
                ("content_hash", models.CharField(max_length=71)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="scenarios.scenarioset",
                    ),
                ),
            ],
            options={
                "db_table": "core_scenario_set_version",
                "ordering": ["scenario_set_id", "version"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioSetVersionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="set_items",
                        to="scenarios.scenariorevision",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="set_items",
                        to="scenarios.scenario",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="scenarios.scenariosetversion",
                    ),
                ),
            ],
            options={
                "db_table": "core_scenario_set_version_item",
                "ordering": ["version_id", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.UniqueConstraint(
                fields=("project", "key"), name="unique_scenario_key_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariorevision",
            constraint=models.UniqueConstraint(
                fields=("scenario", "revision"), name="unique_scenario_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariorevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gt", 0)),
                name="scenario_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenarioset",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_scenario_set_name_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariosetversion",
            constraint=models.UniqueConstraint(
                fields=("scenario_set", "version"), name="unique_set_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariosetversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="set_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariosetversionitem",
            constraint=models.UniqueConstraint(
                fields=("version", "scenario"), name="unique_scenario_in_set_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariosetversionitem",
            constraint=models.UniqueConstraint(
                fields=("version", "position"), name="unique_position_in_set_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariosetversionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gt", 0)),
                name="set_item_position_positive",
            ),
        ),
    ]
