# Generated by Django 5.2.4 on 2026-09-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="workos_user_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
