# Generated by Django 5.2.4 on 2026-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_workos_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
