# Generated by Django 5.2.4 on 2026-09-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditrun",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
