# Generated by Django 5.2.4 on 2026-09-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0002_add_audit_run_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
